export const FontFamily = {
  Poppins_Regular: 'Poppins-Regular',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_Light: 'Poppins-Light',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_Thin: 'Poppins-Thin',
  Poppins_ThinItalic: 'Poppins-ThinItalic',
  Poppins_Black: 'Poppins-Black',
  Poppins_BlackItalic: 'Poppins-BlackItalic',
};
